<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "umfrage"
 *
 * Auto generated by Extension Builder 2015-09-08
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Umfrage',
	'description' => '',
	'category' => 'module',
	'author' => 'Alexander Fuchs',
	'author_email' => 'alexander.fuchs@woehrl.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);