<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "woehrl_onlinebefragung"
 *
 * Auto generated by Extension Builder 2015-07-06
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'WÖHRL Online-Befragung',
	'description' => 'Kunde erhält, je nachdem, ob uns eine NL-Permission vorliegt oder nicht, eine E-Mail oder ein Print-Mailing in dem der Kunde einen Link mitgeschickt bekommt, über den er an unserer Online-Befragung teilnehmen kann',
	'category' => 'plugin',
	'author' => 'Alexander Fuchs',
	'author_email' => 'alexander.fuchs@woehrl.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);