<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "woehrl_newsletter"
 *
 * Auto generated by Extension Builder 2015-02-12
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'WÖHRL Newsletter Registrierung',
	'description' => 'Mit dem WÖHRL-Newsletter erhalten Sie alle Neuigkeiten vorab!

    * Informieren Sie sich über die aktuellsten Mode-Highlights
    * Sichern Sie sich vorab günstige Spezial-Angebote
    * Nehmen Sie an unseren attraktiven Online-Gewinnspielen teil
    * Wissen Sie immer, was aktuell in unseren WÖHRL Häusern passiert',
	'category' => 'plugin',
	'author' => 'Alexander Fuchs',
	'author_email' => 'alexander.fuchs@woehrl.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 1,
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);