<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "woehrl_kassenbongewinnspiel"
 *
 * Auto generated by Extension Builder 2015-03-07
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'WÖHRL KASSENBON-GEWINNSPIEL',
	'description' => 'WENN DIE KASSE ZWEIMAL KLINGELT: UNSER KASSENBON-GEWINNSPIEL.',
	'category' => 'plugin',
	'author' => 'Alexander Fuchs',
	'author_email' => 'alexander.fuchs@woehrl.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.2',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);